### ISSUE TITLE
Add a beginning space on all responses

### ISSUE THREAD

**Issue by odysseyalive** [FartyPants/Playground#13]
I have to remember to do this myself. It might be a nice candidate for a user setting for preference. Some users may even prefer to enter a new line or two.

This would be very helpful when generating the followup response after the bot is cut off.

**Comment by odysseyalive** [comment]
Okay, I just found this option under Parameters and Custom Stopping Strings.

**Comment by CubeTheThird** [comment]
> Okay, I just found this option under Parameters and Custom Stopping Strings.

Are you somehow using the Custom Stopping Strings to add a space or newline after the generation is cut off? Or is there a different setting I'm not seeing? I too would have liked to see a space added when pressing Generate to continue the output, but I don't see how this accomplishes it.
