### ISSUE TITLE
Does this work withOUT LoRA's?

### ISSUE THREAD

**Issue by knight-captain** [FartyPants/Playground#6]
I have a pretty up to date Ooba (<2 weeks) and when I try to load Playground I get the following stack trace:

> 2023-09-25 19:11:15 INFO:Loading the extension "Playground"...
> NEW PEFT is installed
> Loading Paraphrase Template: extensions\Playground\Paraphrase\Basic.txt
> Loaded adapters:
> Traceback (most recent call last):
>   File "D:\oobabooga_windows\text-generation-webui\server.py", line 137, in create_interface
>     extensions_module.create_extensions_tabs()  # Extensions tabs
>   File "D:\oobabooga_windows\text-generation-webui\modules\extensions.py", line 199, in create_extensions_tabs
>     extension.ui()
>   File "D:\oobabooga_windows\text-generation-webui\extensions\Playground\script.py", line 1115, in ui
>     gr_Loralmenu = gr.Radio(choices=get_available_LORA(), value=model_name, label='Activate Loaded LORA adapters', interactive=True)
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 1335, in __init__
>     IOComponent.__init__(
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 211, in __init__
>     load_fn, initial_value = self.get_load_fn_and_initial_value(value)
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 387, in get_load_fn_and_initial_value
>     initial_value = value()
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\transformers\integrations\peft.py", line 308, in active_adapter
>     raise ValueError("No adapter loaded. Please load an adapter first.")
> ValueError: No adapter loaded. Please load an adapter first.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "D:\oobabooga_windows\text-generation-webui\server.py", line 234, in <module>
>     create_interface()
>   File "D:\oobabooga_windows\text-generation-webui\server.py", line 93, in create_interface
>     with gr.Blocks(css=css, analytics_enabled=False, title=title, theme=ui.theme) as shared.gradio['interface']:
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1411, in __exit__
>     self.config = self.get_config_file()
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1378, in get_config_file
>     props = block.get_config() if hasattr(block, "get_config") else {}
>   File "D:\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 1354, in get_config
>     "value": self.value,
> AttributeError: 'Radio' object has no attribute 'value'

The only part of the code that comes from Playground is the:

>  ui
>     gr_Loralmenu = gr.Radio(choices=get_available_LORA(), value=model_name, label='Activate Loaded LORA adapters', interactive=True)

However, I have no LoRA's, so this would be empty. Would this be causing the error? Sorry, my Python is pretty basic.

**Comment by knight-captain** [comment]
I could troubleshoot by loading a LoRA, but I can't seem to find any LLaMa 2 ones easily....

**Comment by knight-captain** [comment]
I trained a fresh LoRA on some of my work, and Playground now loads just fine! 

Is there a way for Playground to bypass the above "get_available_LORA()" for those not planning on using LoRAs?

**Comment by FartyPants** [comment]
Try new version. There are more error checks in it.

**Comment by knight-captain** [comment]
Can now load Playground without LoRA's, thank you!

**Comment by knight-captain** [comment]
Issue resolved
